version: "3.8"

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build: ./src
    env_file: .env
    volumes:
      - ./src:/app
      - static:/app/google_oauth/static
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/app/google_oauth/static
    depends_on:
      - django

volumes:
  pgdata:
  static:
